### ISSUE TITLE
Mismatching types for shared_fmt! on armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by uklotzde** [nu11ptr/flexstr#15]
A build for the `armv7-unknown-linux-gnueabihf` target is failing with the following error on a GitHub Ubuntu x86-64 runner:

```
 error[E0308]: mismatched types
  --> lib/crate/src/file.rs:74:21
   |
74 |                     shared_fmt!("node {node_ref:?} not found");
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `22`, found `10`
   |
   = note: expected union `FlexStr<_, 22, 7, 7>`
              found union `FlexStr<_, 10, 3, 3>`
   = note: this error originates in the macro `shared_fmt` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
```

Obviously a confusion between the host and target platform.

Unfortunately a private project so I can't share any links to the code. We are using `flexstr` in multiple internal crates. It worked flawlessly until recently adding a new internal crate.

**Comment by nu11ptr** [comment]
I'm not understanding how this is a flexstr bug? Somehow you have a mismatch between two different types of string with different sizing params.

**Comment by uklotzde** [comment]
Probably caused by an unrelated issue: https://github.com/HMIProject/open62541/issues/32

Sorry for the noise.
