### ISSUE TITLE
Store the length in the tag?

### ISSUE THREAD

**Issue by epage** [nu11ptr/flexstr#6]
This could allow `FlexStr` to store 23 bytes, instead of 22 bytes.  Unsure if there is extra overhead from doing this that would could make the benefits iffy.

One step further, `compact_str` stores the length, tag. and the final byte in the 24th byte, leveraging unused bits in a terminating UTF-8 character.

**Comment by nu11ptr** [comment]
I saw these optimizations and I have to say, this is probably just a case of different people thinking differently. To me, it is like why get crazy and do bitwise ops for an extra byte? If we had a use case where it was like there is a very popular type of string that is always 23 bytes long, yeah, I'd do it..no brainer, but honestly not seeing the point of the complexity for this one.

**Comment by nu11ptr** [comment]
Now 24 bytes, that is at least semi-interesting...2 more bytes... lol. Could be done. Use the marker as last UTF8 char leaving 64 numbers to use for length and marker. Slight cost to the bitwise ops... worth it? Still not seeing it but I'll think on it more.

**Comment by epage** [comment]
I've mostly felt similar; was just unsure where you land on the complexity / runtime performance / memorry usage trade offs.

Using 23 bytes isn't all that bad on the implementation though how often that 23rd byte really saves you, unsure.

**Comment by nu11ptr** [comment]
1) Stability 2) Speed 3) Complexity :-)

This one actually probably makes more sense for 32-bit now that I think on it (10 bytes vs 12)

**Comment by nu11ptr** [comment]
After thinking on this for the weekend I concluded this optimization isn't right for FlexStr. In the future I will be implementing "jumbo size" options, so it is unclear how much of the `u8` will be needed for length, in some cases most of it. Also, combining with the marker would complicate matching against it which is too key to do in hot spots. In short, closing this one out (for now - will reeval if the situation ever changes).
